# Generated by Django 5.1 on 2024-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=200, unique=True)),
                ('modelo', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('horaEntrada', models.DateTimeField(verbose_name='')),
                ('horaSalida', models.DateTimeField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'autos',
                'verbose_name_plural': 'autos',
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
