# Generated by Django 5.1 on 2024-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroParqueo', '0002_autos_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='autos',
            name='updated',
        ),
        migrations.AlterField(
            model_name='autos',
            name='horaEntrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='autos',
            name='horaSalida',
            field=models.DateTimeField(),
        ),
    ]
